[package]
name = "lommix_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.1", default-features = true, features = [
  "serialize",
  "bevy_asset",
  "bevy_sprite",
  "bevy_core_pipeline",
  "bevy_ui",

  "file_watcher",
] }
bevy-inspector-egui = "0.25.2"
nom = "7.1.3"
quick-xml = { version = "0.36.1" }
ron = "0.8.1"
serde = { version = "1.0.209", features = ["derive"] }
thiserror = "1.0.63"
