[package]
name = "bevy_hui_widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_hui = { path = "../bevy_hui" }
bevy = { version = "0.15", default-features = false, features = ["bevy_ui"] }

[dev-dependencies]
bevy = { version = "0.15", features = ["file_watcher", "multi_threaded"] }
